doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        driver: 'pdo_pgsql'
        server_version: '15'
        mapping_types:
            task_status: task_status
            task_priority: task_priority
        types:
            #ulid: 'Symfony\Component\Uid\Doctrine\UlidType'
            task_status: App\Tasks\Domain\Entity\TaskStatusType
            task_priority: App\Tasks\Domain\Entity\TaskPriorityType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            App:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            Users:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Users/Infrastructure/Database/ORM'
                #dir: '%kernel.project_dir%/src/Users/Domain/Entity'
                prefix: 'App\Users\Domain\Entity'
                alias: Users
            Tasks:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Tasks/Infrastructure/Database/ORM'
                #dir: '%kernel.project_dir%/src/Tasks/Domain/Entity'
                prefix: 'App\Tasks\Domain\Entity'
                alias: Tasks

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
