controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
#    type: attribute
    type: annotation

kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: annotation
